#### Pandas Assignment

1. Refer to googleplaystore.csv file and solve following questions
a. Display First 5 records from Dataframe.
b. Display category with highest number of apps registered.
c. What is the average rating for all the apps
d. Display total number of apps which even supports Andriod version 2.3 and up
e. Impute the missing values available in rating column with respective measure
of central tendency.

In [1]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'googleplaystore.csv', 'Question.ipynb']

In [2]:
#1. Refer to googleplaystore.csv file and solve following questions

In [3]:
import pandas as pd

In [5]:
df=pd.read_csv("googleplaystore.csv")

In [6]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [17]:
##a. Display First 5 records from Dataframe.

In [18]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [12]:
##b. Display category with highest number of apps registered.

In [19]:
df["Category"].value_counts().idxmax()

'FAMILY'

In [20]:
df["Category"].value_counts().head(1)

Category
FAMILY    1972
Name: count, dtype: int64

In [21]:
#c. What is the average rating for all the apps

In [22]:
df["Rating"].mean()

np.float64(4.193338315362443)

In [16]:
# d. Display total number of apps which even supports Andriod version 2.3 and up

In [23]:
(df["Android Ver"]=="2.3 and up").sum()

np.int64(652)

In [24]:
##e. Impute the missing values available in rating column with respective measure of central tendency.

In [25]:
mean_rating=df["Rating"].mean()

In [27]:
df["Rating"]=df["Rating"].fillna(mean_rating)
df["Rating"]

0        4.100000
1        3.900000
2        4.700000
3        4.500000
4        4.300000
           ...
10836    4.500000
10837    5.000000
10838    4.193338
10839    4.500000
10840    4.500000
Name: Rating, Length: 10841, dtype: float64

#### 2. Refer to salaries.xlsx file and solve following questions
a. Check head of the dataframe
b. Find out details about no. of entries & no. of columns in the data frame
c. What is the average base pay?
d. What is the highest amount of overtime pay in the dataset?
e. What is the job title of JOSEPH DRISCOLL?
f. How much does JOSEPH DRISCOLL make (including benefits)?
g. How many unique job titles are there?
h. What are the top 5 common jobs?

In [28]:
##a. Check head of the dataframe

In [2]:
import pandas as pd

In [3]:
df=pd.read_excel("salaries.xlsx")
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,ANTIONETTE GRIFFIN,CLINICAL NURSE SPECIALIST,169572.08,0.00,250.00,NaN,169822.08,169822.08,2011,NaN,San Francisco,NaN
996,997,KATHERINE MAH,CLINICAL NURSE SPECIALIST,169572.06,0.00,250.00,NaN,169822.06,169822.06,2011,NaN,San Francisco,NaN
997,998,CHRISTINE DAVENPORT,CLINICAL NURSE SPECIALIST,169572.05,0.00,250.00,NaN,169822.05,169822.05,2011,NaN,San Francisco,NaN
998,999,ANNE HUGHES,CLINICAL NURSE SPECIALIST,169572.01,0.00,250.00,NaN,169822.01,169822.01,2011,NaN,San Francisco,NaN
999,1000,JOHN FAZIO,CLINICAL NURSE SPECIALIST,169572.00,0.00,250.00,NaN,169822.00,169822.00,2011,NaN,San Francisco,NaN

In [4]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\pradnya\appdata\roaming\python\python314\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\pradnya\appdata\roaming\python\python314\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [6]:
##b. Find out details about no. of entries & no. of columns in the data frame

In [7]:
print("Number of entries:",df.shape[0])
print("Number of columns:",df.shape[1])

Number of entries: 1000
Number of columns: 13

In [8]:
df.shape

(1000, 13)

In [9]:
##c. What is the average base pay?

In [10]:
df["BasePay"].mean()

np.float64(145663.9982)

In [11]:
##d. What is the highest amount of overtime pay in the dataset?

In [12]:
df["OvertimePay"].max()

np.float64(245131.88)

In [13]:
##e. What is the job title of JOSEPH DRISCOLL?

In [14]:
df[df["EmployeeName"]=="JOSEPH DRISCOLL"]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
24,25,JOSEPH DRISCOLL,"CAPTAIN, FIRE SUPPRESSION",140546.86,97868.77,31909.28,NaN,270324.91,270324.91,2011,NaN,San Francisco,NaN

In [15]:
#g. How many unique job titles are there?

In [16]:
df["JobTitle"].nunique()

113

In [17]:
#h. What are the top 5 common jobs?

In [20]:
df["JobTitle"].value_counts().head(5)

JobTitle
FIREFIGHTER                           133
LIEUTENANT, FIRE DEPARTMENT            62
FIRE FIGHTER PARAMEDIC                 43
CAPTAIN, FIRE SUPPRESSION              42
BATTALION CHIEF, (FIRE DEPARTMENT)     41
Name: count, dtype: int64