#### Assignment 3 :DataFrame
Dataset: Consider the following dataset of sales records:
Order ID Customer Product Category Quantity Price Total Sales
1001 Alice Laptop Electronics 2 800 1600
1002 Bob Phone Electronics 1 500 500
1003 Charlie Chair Furniture 4 100 400
1004 Alice Table Furniture 1 250 250
1005 David Laptop Electronics 1 800 800
1006 Charlie Phone Electronics 2 500 1000
1007 Bob Chair Furniture 2 100 200
1008 Alice Phone Electronics 1 500 500

Tasks:
1. Create a DataFrame:
o Load the above dataset into a Pandas DataFrame.
2. Add a New Column:
o Add a column Discount that gives a 10% discount on total
sales.
3. Add a New Row:
o Add a new sales record: Order ID = 1009, Customer =
"Eve", Product = "Tablet", Category = "Electronics",
Quantity = 1, Price = 300, Total Sales = 300.

4. Filter Data:
o Retrieve only the sales records where the Category is
"Electronics".

5. Selection:
o Select the Customer and Total Sales columns.

6. Grouping:
o Group the data by Customer and calculate the total sales per
customer.
7. Sorting:
o Sort the DataFrame based on Total Sales in descending
order.
8. Apply Function:
o Apply a lambda function to create a new column Sales
Category, where values are labeled as "High" if Total Sales >
1000, otherwise "Low".

9. Save DataFrame:
o Save the final DataFrame as a CSV file named sales_data.csv.

In [3]:
##1. Create a DataFrame:
#o Load the above dataset into a Pandas DataFrame.

In [4]:
import pandas as pd

In [6]:
data={
    "Order ID":[1001,1002,1003,1004,1005,1006,1007,1008],
    "Customer":["Alice","Bob","Charlie","Alice","David","Charlie","Bob","Alice"],
    "Product":["Laptop","Phone","chair","Table","Laptop","Phone","Chair","Phone"],
    "Category":["Electronics","Electronics","Furniture","Furniture","Electronics","Electronics","Furniture","Electronics"],
    "Quantity":[2,1,4,1,1,2,2,1],
    "Price":[800,500,100,250,800,500,100,500],
    "Total Sales":[1600,500,400,250,800,1000,200,500]
}

df=pd.DataFrame(data)
df

   Order ID Customer Product     Category  Quantity  Price  Total Sales
0      1001    Alice  Laptop  Electronics         2    800         1600
1      1002      Bob   Phone  Electronics         1    500          500
2      1003  Charlie   chair    Furniture         4    100          400
3      1004    Alice   Table    Furniture         1    250          250
4      1005    David  Laptop  Electronics         1    800          800
5      1006  Charlie   Phone  Electronics         2    500         1000
6      1007      Bob   Chair    Furniture         2    100          200
7      1008    Alice   Phone  Electronics         1    500          500

In [8]:
##2. Add a New Column:
#o Add a column Discount that gives a 10% discount on total
#sales.

In [9]:
df["Discount"]=df["Total Sales"]*0.10
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0

In [10]:
##3. Add a New Row:
# o Add a new sales record: Order ID = 1009, Customer =
# "Eve", Product = "Tablet", Category = "Electronics",
# Quantity = 1, Price = 300, Total Sales = 300.

In [12]:
new_row={
    "Order ID":1009,
    "Customer":"Eve",
    "Product":"Table",
    "Category":"Electronics",
    "Quantity":1,
    "Price":300,
    "Total Sales":300,
    "Discount":300*0.10
}
df.loc[len(df)]=new_row
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,1009,Eve,Table,Electronics,1,300,300,30.0

In [13]:
# ##4. Filter Data:
# o Retrieve only the sales records where the Category is
# "Electronics".

In [14]:
electronics=df[df["Category"]=="Electronics"]
electronics

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,1009,Eve,Table,Electronics,1,300,300,30.0

In [15]:
# 4. Filter Data:
# o Retrieve only the sales records where the Category is
# "Electronics".

In [16]:
electronics=df[df["Category"]=="Electronics"]
electronics

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,1009,Eve,Table,Electronics,1,300,300,30.0

In [17]:
# #5.5. Selection:
# o Select the Customer and Total Sales columns.

In [18]:
selected=df[["Customer","Total Sales"]]
selected

  Customer  Total Sales
0    Alice         1600
1      Bob          500
2  Charlie          400
3    Alice          250
4    David          800
5  Charlie         1000
6      Bob          200
7    Alice          500
8      Eve          300

In [19]:
# ##6.6. Grouping:
# o Group the data by Customer and calculate the total sales per
# customer.

In [22]:
customer_sales=df.groupby("Customer")["Total Sales"].sum()
customer_sales

Customer
Alice      2350
Bob         700
Charlie    1400
David       800
Eve         300
Name: Total Sales, dtype: int64

In [23]:
# ##7. Sorting:
# o Sort the DataFrame based on Total Sales in descending
# order.

In [24]:
sorted_df=df.sort_values(by="Total Sales",
                         ascending=False)
sorted_df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,chair,Furniture,4,100,400,40.0
8,1009,Eve,Table,Electronics,1,300,300,30.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0

In [25]:
# ##8. Apply Function:
# o Apply a lambda function to create a new column Sales
# Category, where values are labeled as "High" if Total Sales >
# 1000, otherwise "Low".

In [26]:
df["Sales Category"]=df["Total Sales"].apply(lambda x:"High" if x>1000 else "Low")
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount,Sales Category
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0,High
1,1002,Bob,Phone,Electronics,1,500,500,50.0,Low
2,1003,Charlie,chair,Furniture,4,100,400,40.0,Low
3,1004,Alice,Table,Furniture,1,250,250,25.0,Low
4,1005,David,Laptop,Electronics,1,800,800,80.0,Low
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0,Low
6,1007,Bob,Chair,Furniture,2,100,200,20.0,Low
7,1008,Alice,Phone,Electronics,1,500,500,50.0,Low
8,1009,Eve,Table,Electronics,1,300,300,30.0,Low

In [27]:
# 9. Save DataFrame:
# o Save the final DataFrame as a CSV file named sales_data.csv.

In [28]:
df.to_csv("sales_data.csv",index=False)
print("DataFrame saved successfully as sales_data.csv")

DataFrame saved successfully as sales_data.csv